name: Build And Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image in CI
        run: docker build . -t healthapp-ci
      - name: install packages
        run: pip install -r requirements.txt
      - name: run login
        run: python manage.py test
      - name: run activity functions (add/edit/view/delete)
        run: python manage.py test fitness


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image in CI
      run: docker build . -t healthapp-ci
