name: Local Docker CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image locally
      run: docker build . -t healthapp-local

    - name: Run container and test
      run: |
        docker run -d --name healthapp -p 8000:8000 healthapp-local
        sleep 5  # wait for container to boot
        curl -f http://localhost:8000  # basic health check
