name: Registration Test CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      web:
        build:
          context: .
        ports:
          - 8000:8000
        options: >-
          --health-cmd="curl --fail http://localhost:8000 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
    - uses: actions/checkout@v4

    - name: Install Python and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for Django to be ready
      run: sleep 20

    - name: Run registration test
      run: python register/test.py